### PR TITLE
Update skeleton.css

### PR DESCRIPTION
**Pull request by HexM7**
Solves the unwanted misplacement of skeleton child (used to have a gap at the top in rare cases).

### CODE REVIEW

**Comment by srmagura** [comment]
Hey @HexM7, would you be able to provide a CodeSandbox that shows the problem this PR solves?

**Comment by HexM7** [comment]
Here is the demo: https://codesandbox.io/s/serverless-darkness-2ipti?file=/src/App.js
Everything is fine on the initial render, but as you change something in the CSS file you'll notice the animated element getting shifted a bit. I have attached a screenshot.

serverless-darkness-2ipti - CodeSandbox - Google Chrome 2_5_2022 4_39_08 PM

**Comment by srmagura** [comment]
I'm just seeing the default React template when I visit that link. Did you send the correct link?

image

**Comment by HexM7** [comment]
I'm extremely sorry, I'm new to CodeSandBox. Here's the StackBlitz project: https://stackblitz.com/edit/react-vqvafn?file=src%2FApp.js

**Comment by srmagura** [comment]
Thanks @HexM7! I don't understand why `top: 0` is required in this case, but it shouldn't have any negative side effects. I will work on getting this ready for release.

**Pull request merged**
