### PR TITLE
Added speed proptype of skeleton loading

### PR DESCRIPTION
**Pull request by AG-Systems**

### CODE REVIEW

**Comment by dvtng** [comment]
Thanks, this looks good! What do you think about changing the prop from speed to duration? Speed implies a multiplier on the default speed, while duration is more explicitly about the length of animation.

**Comment by AG-Systems** [comment]
By duration do you mean how long it takes for it to take to complete one cycle?

**Comment by dvtng** [comment]
Yes, exactly that. The implementation doesn't need to change, just the name of the prop :)

**Comment by AG-Systems** [comment]
Sweet  easy fix. I will do it asap!

**Comment by AG-Systems** [comment]
I made the following changes! :)

**Comment by dvtng** [comment]
Released in version 0.4.0!

**Pull request merged**
