### PR TITLE
Feature/add ssr support

### PR DESCRIPTION
**Pull request by UNLRN**
Adds support for SSR

### CODE REVIEW

**Comment by camdagr8** [comment]
@dvtng Any idea when you can get this merged?

**Comment by dvtng** [comment]
Thanks for the PR! Let me check this out and get back to you within a week.

**Comment by bytheway875** [comment]
Bump bump any updates on this?

**Comment by dvtng** [comment]
Sorry for the delay all! I wanted to find a solution that didn't require importing a css file (and setting up css modules if you didn't otherwise need it). I've just released 0.6.0 which uses Emotion under the hood to support SSR. If you already use Emotion for your own CSS, then great -- it'll just work for you. Otherwise, please see Emotion docs for how to enable SSR: https://emotion.sh/docs/ssr

**Pull request closed without merging**
