### PR TITLE
Circulair prop

### PR DESCRIPTION
**Pull request by glenngijsberts**
Based on open issue #9 I've added a small feature to make the skeleton circulair. This will make it easy to compose for example user cards with profile pictures. To make this work I also added a height prop to manage the height of the skeleton. This default prop will be null so this won't affect `skeletons` that are used by adapting to text.

The reason why I added these props is because this package now is only supporting skeleton loading for texts. Imho, most of the time it's not text you would like to cover with skeleton loading.

I've added stories to the tests. Please make sure to also update the npm package when this PR get's accepted since I would like to use this package heavily.

### CODE REVIEW

**Comment by simpson** [comment]
Height would be really helpful, any updates on this?

**Comment by glenngijsberts** [comment]
@simpson It's been 10 days since my PR, unfort. no comment so far from the maintainer.

**Comment by simpson** [comment]
@dvtng any thoughts on this? The height prop would be extremely helpful for achieving additional elements

**Comment by abhijitparida** [comment]
@dvtng please merge

**Comment by dvtng** [comment]
Sorry for the delay all.  This is now merged and published as in version 1.0.0!

**Pull request merged**
