### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by IcedMonk**
Updated the year to the current year

### CODE REVIEW

**Comment by srmagura** [comment]
Is this necessary for legal reasons?

**Comment by IcedMonk** [comment]
It is generally good practice to update the year in the copyright notice of a project's license file every year. This helps to accurately reflect the span of time during which the project has been developed and maintained, and can help to establish the project's ownership and provenance.

For example, if a project is initially released in 2021 and its license file includes a copyright notice that reads "Copyright 2021 [project creator]", the notice should be updated to "Copyright 2021-2022 [project creator]" at the start of 2022, and so on. This helps to clearly establish the length of time during which the project has been available and the rights granted to users of the project.

Updating the year in the copyright notice of a project's license file is not strictly required, but it is a good practice that can help to ensure the accuracy and clarity of the license terms. It is also important to ensure that the correct license terms are applied to a project, as the terms of different licenses can vary significantly.

**Comment by srmagura** [comment]
Thank you 🙂

**Comment by IcedMonk** [comment]
> Thank you 🙂

**Sam** Thank you so much for accepting and merging my pull request! It was an honor to contribute to your library, and I'm grateful for the opportunity. Your work is a true inspiration to me, and I look up to you as a role model. I'm thrilled to be able to use your library, Emotion, on a daily basis with my co-workers. I hope to contribute even more valuable pull requests in the future, and I'm eager to learn as much as I can about open source. Is it possible to connect on a platform like Discord or another chat service? I'd love to continue the conversation and learn more from you. Thank you again for your guidance and support!

**Pull request merged**
